console.log('Hello world');
console.log("Hello");
let myName = 'Valery';
let myAge = '30';
console.log('Мое имя: ' + myName);
console.log('Мой возраст: ' + myAge +' лет');
console.log(myAge + myName);
console.log(`${myAge}  ${myName}`);
console.log(`Мое имя:  ${myName}`);
// alert('Hello');